export const PAGE_PATH = {
  HOME: '/',
  WALLET: '/wallet',
  LOGIN: '/login',
  SAVINGS: '/savings',
  DEPOSIT: '/deposit',
  DEPOSIT_RESULT: '/deposit/result',
  ACCOUNT_CREATION: '/account-creation',
  GAME: '/game',
  SHOP: '/shop',
  GACHA: '/gacha',
  GACHA_ROLLING: '/gacha/rolling',
  DECO: '/deco',
  COLORTEST: '/colortest',
  NOT_FOUND: '*',
} as const;
